### ISSUE TITLE
Unable to place call on Android 11 Automotive

### ISSUE THREAD

**Issue by dhondgeswayam** [android-rpi/device_arpi_rpi4#94]
I have flashed android 11 automotive to the Raspberry pi 4 model b. When I connect my phone to the raspberry pi via bluetooth and try placing a calling using the Phone application I am unable to place the call. Similarly when I try calling to the raspberry pi  from another device, the bluetooth gets turned off and the call can be seen on the User phone.
Here are the logs while peforming the above operation :
--------Logs for dialer application on RPi4-------------------------------

2021-12-29 18:23:25.657 3773-3773/? E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.android.bluetooth, PID: 3773
java.lang.RuntimeException: Error receiving broadcast Intent { act=android.bluetooth.headsetclient.profile.action.AG_CALL_CHANGED flg=0x10000010 (has extras) } in com.android.bluetooth.hfpclient.connserv.HfpClientConnectionService$1@e95b52f
at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1590)
at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7660)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.SecurityException: This PhoneAccountHandle is not registered for this user!
at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
at android.os.Parcel.createException(Parcel.java:2357)
at android.os.Parcel.readException(Parcel.java:2340)
at android.os.Parcel.readException(Parcel.java:2282)
at com.android.internal.telecom.ITelecomService$Stub$Proxy.addNewUnknownCall(ITelecomService.java:2706)
at android.telecom.TelecomManager.addNewUnknownCall(TelecomManager.java:1929)
at com.android.bluetooth.hfpclient.connserv.HfpClientDeviceBlock.handleCall(HfpClientDeviceBlock.java:182)
at com.android.bluetooth.hfpclient.connserv.HfpClientConnectionService$1.onReceive(HfpClientConnectionService.java:112)
at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1580)
at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7660)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: android.os.RemoteException: Remote stack trace:
at com.android.server.telecom.TelecomServiceImpl.enforcePhoneAccountIsRegisteredEnabled(TelecomServiceImpl.java:2038)
at com.android.server.telecom.TelecomServiceImpl.access$3100(TelecomServiceImpl.java:75)
at com.android.server.telecom.TelecomServiceImpl$1.addNewUnknownCall(TelecomServiceImpl.java:1340)
at com.android.internal.telecom.ITelecomService$Stub.onTransact(ITelecomService.java:1289)
at android.os.Binder.execTransactInternal(Binder.java:1159)

**Comment by Xiaotaoxu** [comment]
I got the same problem. Does anyone know how to solve this problem?
